# Site settings
title: Invasion of Small Cubes
email: dierre put@here gmail.com
description: > # These are some of my notes. I'm lazy so bear with me. Programming and other stuff.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://invasionofsmallcubes.github.io" # the base hostname & protocol for your site
twitter_username: IsTDDDeadYet
github_username:  invasionofsmallcubes

# Build settings
markdown: kramdown
